### ISSUE TITLE
Apple Silicon Not Supported

### ISSUE THREAD

**Issue by gsornsen** [FuzzFoundation/WKTPlot#14]
Mac M1 chipset is not supported due to [dependency on Shapely](https://github.com/shapely/shapely/issues/1040).

**Comment by Jurisak** [comment]
Works on my side with M1 Pro chipset.

**Comment by misimpso** [comment]
@Jurisak Awesome! Which version of Shapely are you using?

**Comment by gsornsen** [comment]
Thanks @Jurisak - Looks like Shapely fixed it in >=1.8.1 -- PR incoming

**Comment by Jurisak** [comment]
It was working with shapely 1.8.0 on my side.

BTW I am running it on python 3.10. You can include it in supported versions.

**Comment by misimpso** [comment]
Nice. I think Shapely was the main requirement that was causing us from supporting 3.10, but it looks like they have fixed it on their end. I just tried on Windows with 3.10.1 and was able to run it as well.

**Comment by misimpso** [comment]
Python 3.10 is now officially supported!
