### ISSUE TITLE
Allow user to disable automatic save

### ISSUE THREAD

**Issue by rsmith013** [FuzzFoundation/WKTPlot#26]
**Is your feature request related to a problem? Please describe.**
I am using WKTPlot within a Jupyter Notebook. You can use Bokeh to render the plot inline `output_notebook()` but WKTPlot still enforces a save. This opens a new tab and is annoying.

**Describe the solution you'd like**
Add an optional flag to disable the default behaviour

**Describe alternatives you've considered**

**Additional context**

**Comment by misimpso** [comment]
Thank you for the feedback and the PR. I want to make this library more notebook friendly so any annoyances should be documented and fixed. Let me review your PR so we can get it in.

**Comment by misimpso** [comment]
This has been fixed as part of the latest release - https://github.com/FuzzFoundation/WKTPlot/releases/tag/v2.3.0
