### ISSUE TITLE
Error importing WKTPlot

### ISSUE THREAD

**Issue by ThomasThelen** [FuzzFoundation/WKTPlot#29]
**Describe the bug**
When attempting to import WKTPlot, I get the error shown in the screenshots section. It appears that I'm missing wktplot.common. I included a screenshot of the instillation directory to show that the file is missing the `common` folder.

**To Reproduce**
1. Open a new terminal
2. pip install WKTPlot
3. python3
4. from wktplot import WKTPlot
5. See the error below

**Screenshots**
```
Traceback (most recent call last):
  File "/Users/thomas/sdss-demo/roads.py", line 4, in <module>
    from wktplot import WKTPlot
  File "/Users/thomas/sdss-demo/venv/lib/python3.9/site-packages/wktplot/__init__.py", line 1, in <module>
    from .plots.standard import WKTPlot  # noqa: F401
  File "/Users/thomas/sdss-demo/venv/lib/python3.9/site-packages/wktplot/plots/standard.py", line 5, in <module>
    from wktplot.common.file_utils import get_random_string, sanitize_text
ModuleNotFoundError: No module named 'wktplot.common'
```
<img width="763" alt="Screen Shot 2022-08-15 at 11 29 52 AM" src="https://user-images.githubusercontent.com/9289652/184694267-2c7b5ca9-564a-4171-a7d1-3c31581ffa93.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.6.2

**Additional context**

**Comment by misimpso** [comment]
Thanks for creating this issue. Looks like the folder got skipped over when the package was build for some reason. I will look into this tonight.

**Comment by misimpso** [comment]
This should be fixed from this latest PR - https://github.com/FuzzFoundation/WKTPlot/pull/30

**Comment by misimpso** [comment]
Release v2.3.1 is now published with this fix: https://github.com/FuzzFoundation/WKTPlot/releases/tag/v2.3.1
